### ISSUE TITLE
discover error

### ISSUE THREAD

**Issue by erdoukki** [robinbowes/net-udap#3]
with svn 1.0.x I get a discover error

.../UDAP/1.0.x$ ./scripts/udap_shell.pl 
UDAP> discover
info: **\* Broadcasting adv_discovery message to MAC address 00:00:00:00:00:00 on 255.255.255.255
info:   adv_discovery response received from 00:04:20:07:2a:b2
ucp_method get_uuid callback not implemented yet at .../UDAP/1.0.x/scripts/../src/Net-UDAP/lib/Net/UDAP.pm line 292.
Raw msg:
          00 01 02 03 04 05 06 07 - 08 09 0A 0B 0C 0D 0E 0F  0123456789ABCDEF

00000000  00 01 00 04 20 07 2A B2 - 00 01 00 04 20 2C 53 FC  .... .*..... ,S.
00000010  00 01 C0 01 01 00 01 00 - 01 00 0B                 ...........
ucp_method invalid or not defined. at .../UDAP/1.0.x/scripts/../src/Net-UDAP/lib/Net/UDAP/Shell.pm line 153.

**Comment by robinbowes** [comment]
Fixed in #8
