### ISSUE TITLE
UDAP not writing to Duet receiver?

### ISSUE THREAD

**Issue by incansvl** [robinbowes/net-udap#6]
Just like @aidyw I have a Duet receiver that has done sterling service for years, but the controller died some time ago, and the Duet's been getting flakey on my network. UDAP looked like the tool to attempt a rescue.

My attempts to run the precompiled/packaged copy of UDAP 1.0.0 on Windows failed. The tool was emitting a slew of warnings about missing modules and suchlike so I didn't have much hope.

However, I got an installation on Linux (Debian Buster/Sid) running, once I had sorted out all the missing CPAN dependencies.

Current State
------------------
The tool runs without error, finds the Duet  (temporarily on a  wired ethernet i/f), and reads the settings, which do look a bit hinky. They show a mixture of my old Squeezecenter server address (192.168.0.41), and the current one (192.168.0.40). There's also a lan network address and subnet mask that I don't recognise, but these are maybe factory defaults as the device was always used wirelessly up until now.

```
UDAP [1] (squeezebox 172dd2)> list
             bridging: 0
             hostname: Lounge
            interface: 0
          lan_gateway: 0.0.0.0
          lan_ip_mode: 1
  lan_network_address: 169.254.151.3
      lan_subnet_mask: 255.255.0.0
          primary_dns: 0.0.0.0
        secondary_dns: 0.0.0.0
       server_address: 192.168.0.40
squeezecenter_address: 192.168.0.41
   squeezecenter_name: Queeg
        wireless_SSID: {private SSID}
     wireless_channel: 6
      wireless_keylen: 0
        wireless_mode: 0
   wireless_region_id: 14
   wireless_wep_key_0: 00000000000000000000000000
   wireless_wep_key_1: 00000000000000000000000000
   wireless_wep_key_2: 00000000000000000000000000
   wireless_wep_key_3: 00000000000000000000000000
      wireless_wep_on: 0
  wireless_wpa_cipher: 3
    wireless_wpa_mode: 2
      wireless_wpa_on: 1
     wireless_wpa_psk: {private WPA2 key}
```
Symptoms
---------------
I tried to change the settings to try to move the Duet temporarily onto the hard wired interface, just to prove it's working-

UDAP [1] (squeezebox 172dd2)> set lan_network_address=192.168.0.51 lan_subnet_mask=255.255.255.0 squeezecenter_address=192.168.0.40 squeezecenter_name=Holly interface=1

But when I write this to the client and reset it. nothing changes ?! I have to put the Duet back into "init" mode for UDAP to find it (by holding the front panel button until it slow-blinks red), and when I d so and list the settings they are all exactly as they started, nothing has changed.

I've tried power cycling the Duet after writing the settings, but nothing seems to "stick".

Any idea what is happening here? I'm running UDAP as a normal user rather than root, which is generally safer, and there are no access errors showing up. Does UDAP need to run as root to write to the device?

**Comment by robinbowes** [comment]
@incansvl I apologise that it's taken > 5 years to respond to this. I am going to assume that you either fixed the issue, or no longer use the Receiver. Please re-open the request, or create another one if you still need help.
