### ISSUE TITLE
crash on discover response from Squeezebox Radio

### ISSUE THREAD

**Issue by 0xabu** [robinbowes/net-udap#7]
I was hoping to use this to change the server address on a Squeebox Radio, but it crashes in discover:
```
UDAP> discover
info: <<< Broadcasting adv_discovery message to MAC address 00:00:00:00:00:00 on 255.255.255.255
info: >>> adv_discovery response received from 00:04:20:28:36:02
Raw msg:
00 01 00 04 20 28 36 02 00 01 00 04 20 28 36 02 00 01 C0 01 01 00 01 00 01 00 0B ucp_method invalid or not defined. at src/Net-UDAP/lib/Net/UDAP/Shell.pm line 147.
```

**Comment by robinbowes** [comment]
@0xabu This code was written to work with the Squeezebox Receiver, and doesn't handle the UCP method `00 0B` (get_uuid). I don't have a radio to test with so I am unlikely to be able to fix it.

I've put together a speculative workaround that *may* prevent the crash, but it's not tested, and won't help if the get_uuid message needs to be processed.

Can you try the code on the [get_uuid_workaround](https://github.com/robinbowes/net-udap/tree/get_uuid_workaround) branch and let me know if it works?

**Comment by 0xabu** [comment]
Hi @robinbowes, thanks for the quick reply. Your change fixes the crash, but doesn't seem to allow configuration:
```
UDAP> discover
info: <<< Broadcasting adv_discovery message to MAC address 00:00:00:00:00:00 on 255.255.255.255
info: >>> adv_discovery response received from 00:04:20:28:36:02
info: >>> adv_discovery response received from 00:04:20:28:36:02
info: >>> adv_discovery response received from 00:04:20:28:36:02
info: >>> adv_discovery response received from 00:04:20:28:36:02
Raw msg:
00 01 00 04 20 28 36 02 00 01 00 04 20 28 36 02 00 01 C0 01 01 00 01 00 01 00 0B info: >>> get_uuid response received from 00:04:20:28:36:02
info: <<< Broadcasting get_ip message to MAC address 00:04:20:28:36:02 on 255.255.255.255
info: <<< Broadcasting get_data message to MAC address 00:04:20:28:36:02 on 255.255.255.255
UDAP> list
 #    MAC Address    Type       Status
== ================= ========== ===============
 1 00:04:20:28:36:02 baby       wait_slimserver
UDAP> conf 1
UDAP [1] (baby 283602)> list
hostname: Squeezebox Radio
UDAP [1] (baby 283602)> set
UDAP [1] (baby 283602)> fields
             bridging: Use device as a wireless bridge (not sure about this)
             hostname: Device hostname (is this set automatically?)
            interface: 0 - wireless, 1 - wired (is set to 128 after factory reset)
          lan_gateway: IP address of default network gateway, (e.g. 192.168.1.1)
          lan_ip_mode: 0 - Use static IP details, 1 - use DHCP to discover IP details
  lan_network_address: IP address of device, (e.g. 192.168.1.10)
      lan_subnet_mask: Subnet mask of local network, (e.g. 255.255.255.0)
          primary_dns: IP address of primary DNS server
        secondary_dns: IP address of secondary DNS server
       server_address: IP address of currently active server (either Squeezenetwork or local server
squeezecenter_address: IP address of local Squeezecenter server
   squeezecenter_name: Name of local Squeezecenter server (???)
        wireless_SSID: Wireless network name
     wireless_channel: Wireless channel (used by AdHoc mode???)
      wireless_keylen: Length of wireless key, (0 - 64-bit, 1 - 128-bit)
        wireless_mode: 0 - Infrastructure, 1 - Ad Hoc
   wireless_region_id: 4 - US, 6 - CA, 7 - AU, 13 - FR, 14 - EU, 16 - JP, 21 - TW, 23 - CH
   wireless_wep_key_0: WEP Key 0 - enter in hex
   wireless_wep_key_1: WEP Key 1 - enter in hex
   wireless_wep_key_2: WEP Key 2 - enter in hex
   wireless_wep_key_3: WEP Key 3 - enter in hex
      wireless_wep_on: 0 - WEP Off, 1 - WEP On
  wireless_wpa_cipher: 1 - TKIP, 2 - AES, 3 - TKIP & AES
    wireless_wpa_mode: 1 - WPA, 2 - WPA2
      wireless_wpa_on: 0 - WPA Off, 1 - WPA On
     wireless_wpa_psk: WPA Public Shared Key
UDAP [1] (baby 283602)> list server_address
UDAP [1] (baby 283602)>
```

*However* because most (all?) networking-related parameters can be set through the UI on the radio itself, it isn't really necessary to use this code. I had thought I needed this tool because my radio was stuck trying to connect to mysqueezebox.com. Just in case someone in the same predicament finds this issue in the future, the fix was:
 1. ensure that LMS sees and responds to discover broadcasts from the device (if running in [a docker container](https://hub.docker.com/r/lmscommunity/logitechmediaserver), it's necessary to use host networking mode)
 2. use a long press on the back button to exit setup and find the option to connect to a local server

**Comment by robinbowes** [comment]
Hi @0xabu,

I'm not sure if the device needs to be in a special mode to accept the configuration packets. The Receiver needs to be in setup mode - see https://wiki.slimdevices.com/index.php/SBR_front_button_and_LED.html

Also, you don't seemed to have used the right commands to attempt to configure the device. The correct sequence of commands to set the server address is something like this:

```
discover
conf 1
set squeezecenter_address=192.168.1.150
save_data
reset
```

Finally,  I'm glad you're sorted, regardless!

**Comment by 0xabu** [comment]
Yeah, sorry I didn't try too hard because I expected from experience with the receiver that either `list` or `set` (I forget which) would show me a lot more than the hostname. And indeed it's not clear how to put the radio into setup mode -- the above attempt was made after a factory reset, when it was on the wired network trying and failing to connect to mysqueezebox.com.

BTW, I don't think it would hurt to merge your change regardless -- I've previously had problems configuring my receiver as long as the radio was online because its discover response would crash the script. This appears to at least fix that!

**Comment by robinbowes** [comment]
> BTW, I don't think it would hurt to merge your change regardless

I agree. I'll do that now.

Cheers!

R.
